### ISSUE TITLE
AVA video data problem

### ISSUE THREAD

**Issue by wangaoqi-waq** [facebookresearch/SlowFast#165]
I downloaded AVA video data based on DATASET. Md, but some videos failed to download for some reason. I used downloadable videos to process the data and test the results. There is an error, great video worker, can you help me to see how to solve it?
The command I'm running is:(pytorch) root@waq:~/slowfast# python tools/run_net.py --cfg configs/AVA/c2/SLOWFAST_32x2_R101_50_50_v2.1.yaml
The results of：
[INFO: test_net.py:  123]: Test with config:
[INFO: test_net.py:  124]: AVA:
  ANNOTATION_DIR: /data/ava/annotations/
  BGR: False
  DETECTION_SCORE_THRESH: 0.8
  EXCLUSION_FILE: ava_val_excluded_timestamps_v2.1.csv
  FRAME_DIR: /data/ava/frames/
  FRAME_LIST_DIR: /data/ava/frame_lists/
  FULL_TEST_ON_VAL: False
  GROUNDTRUTH_FILE: ava_val_v2.1.csv
  IMG_PROC_BACKEND: cv2
  LABEL_MAP_FILE: ava_action_list_v2.1_for_activitynet_2018.pbtxt
  TEST_FORCE_FLIP: False
  TEST_LISTS: ['val.csv']
  TEST_PREDICT_BOX_LISTS: ['person_box_67091280_iou90/ava_detection_val_boxes_and_labels.csv']
  TRAIN_GT_BOX_LISTS: ['ava_train_v2.1.csv']
  TRAIN_LISTS: ['train.csv']
  TRAIN_PCA_EIGVAL: [0.225, 0.224, 0.229]
  TRAIN_PCA_EIGVEC: [[-0.5675, 0.7192, 0.4009], [-0.5808, -0.0045, -0.814], [-0.5836, -0.6948, 0.4203]]
  TRAIN_PCA_JITTER_ONLY: True
  TRAIN_PREDICT_BOX_LISTS: []
  TRAIN_USE_COLOR_AUGMENTATION: False
BN:
  EPSILON: 1e-05
  MOMENTUM: 0.1
  NUM_BATCHES_PRECISE: 200
  USE_PRECISE_STATS: False
  WEIGHT_DECAY: 0.0
DATA:
  CROP_SIZE: 224
  DECODING_BACKEND: pyav
  INPUT_CHANNEL_NUM: [3, 3]
  INV_UNIFORM_SAMPLE: False
  MEAN: [0.45, 0.45, 0.45]
  NUM_FRAMES: 32
  PATH_PREFIX: 
  PATH_TO_DATA_DIR: 
  SAMPLING_RATE: 2
  STD: [0.225, 0.225, 0.225]
  TARGET_FPS: 30
  TEST_CROP_SIZE: 256
  TRAIN_CROP_SIZE: 224
  TRAIN_JITTER_SCALES: [256, 320]
DATA_LOADER:
  ENABLE_MULTI_THREAD_DECODE: False
  NUM_WORKERS: 0
  PIN_MEMORY: True
DETECTION:
  ALIGNED: False
  ENABLE: True
  ROI_XFORM_RESOLUTION: 7
  SPATIAL_SCALE_FACTOR: 16
DIST_BACKEND: nccl
LOG_PERIOD: 10
MODEL:
  ARCH: slowfast
  DROPOUT_RATE: 0.5
  FC_INIT_STD: 0.01
  LOSS_FUNC: bce
  MODEL_NAME: SlowFast
  MULTI_PATHWAY_ARCH: ['slowfast']
  NUM_CLASSES: 80
  SINGLE_PATHWAY_ARCH: ['c2d', 'i3d', 'slowonly']
NONLOCAL:
  GROUP: [[1, 1], [1, 1], [1, 1], [1, 1]]
  INSTANTIATION: dot_product
  LOCATION: [[[], []], [[], []], [[6, 13, 20], []], [[], []]]
  POOL: [[[2, 2, 2], [2, 2, 2]], [[2, 2, 2], [2, 2, 2]], [[2, 2, 2], [2, 2, 2]], [[2, 2, 2], [2, 2, 2]]]
NUM_GPUS: 1
NUM_SHARDS: 1
OUTPUT_DIR: .
RESNET:
  DEPTH: 101
  INPLACE_RELU: True
  NUM_BLOCK_TEMP_KERNEL: [[3, 3], [4, 4], [6, 6], [3, 3]]
  NUM_GROUPS: 1
  SPATIAL_DILATIONS: [[1, 1], [1, 1], [1, 1], [2, 2]]
  SPATIAL_STRIDES: [[1, 1], [2, 2], [2, 2], [1, 1]]
  STRIDE_1X1: False
  TRANS_FUNC: bottleneck_transform
  WIDTH_PER_GROUP: 64
  ZERO_INIT_FINAL_BN: True
RNG_SEED: 0
SHARD_ID: 0
SLOWFAST:
  ALPHA: 4
  BETA_INV: 8
  FUSION_CONV_CHANNEL_RATIO: 2
  FUSION_KERNEL_SZ: 5
SOLVER:
  BASE_LR: 0.1
  DAMPENING: 0.0
  GAMMA: 0.1
  LRS: []
  LR_POLICY: cosine
  MAX_EPOCH: 300
  MOMENTUM: 0.9
  NESTEROV: True
  OPTIMIZING_METHOD: sgd
  STEPS: []
  STEP_SIZE: 1
  WARMUP_EPOCHS: 0
  WARMUP_FACTOR: 0.1
  WARMUP_START_LR: 0.01
  WEIGHT_DECAY: 1e-07
TEST:
  BATCH_SIZE: 1
  CHECKPOINT_FILE_PATH: 
  CHECKPOINT_TYPE: pytorch
  DATASET: ava
  ENABLE: True
  NUM_ENSEMBLE_VIEWS: 10
  NUM_SPATIAL_CROPS: 3
TRAIN:
  AUTO_RESUME: True
  BATCH_SIZE: 4
  CHECKPOINT_FILE_PATH: /root/slowfast/checkpoints/SLOWFAST_32x2_R101_50_50_v2.1.pkl
  CHECKPOINT_INFLATE: False
  CHECKPOINT_PERIOD: 1
  CHECKPOINT_TYPE: pytorch
  DATASET: ava
  ENABLE: False
  EVAL_PERIOD: 1
....................................#omit
[INFO: logging.py:   67]: json_stats: {"_type": "test_iter", "cur_iter": "5000", "eta": "8:09:21", "mode": "test", "time_diff": 0.613877}
[WARNING: utils.py:   33]: Reading failed. Will retry.
[WARNING: utils.py:   33]: Reading failed. Will retry.
[WARNING: utils.py:   33]: Reading failed. Will retry.
[WARNING: utils.py:   33]: Reading failed. Will retry.
[WARNING: utils.py:   33]: Reading failed. Will retry.
[WARNING: utils.py:   33]: Reading failed. Will retry.
[WARNING: utils.py:   33]: Reading failed. Will retry.
[WARNING: utils.py:   33]: Reading failed. Will retry.
[WARNING: utils.py:   33]: Reading failed. Will retry.
[WARNING: utils.py:   33]: Reading failed. Will retry.
Traceback (most recent call last):
  File "tools/run_net.py", line 152, in <module>
    main()
  File "tools/run_net.py", line 147, in main
    test(cfg=cfg)
  File "/root/slowfast/tools/test_net.py", line 183, in test
    perform_test(test_loader, model, test_meter, cfg)
  File "/home/waq/anaconda3/envs/pytorch/lib/python3.6/site-packages/torch/autograd/grad_mode.py", line 49, in decorate_no_grad
    return func(*args, **kwargs)
  File "/root/slowfast/tools/test_net.py", line 44, in perform_test
    for cur_iter, (inputs, labels, video_idx, meta) in enumerate(test_loader):
  File "/home/waq/anaconda3/envs/pytorch/lib/python3.6/site-packages/torch/utils/data/dataloader.py", line 345, in __next__
    data = self._next_data()
  File "/home/waq/anaconda3/envs/pytorch/lib/python3.6/site-packages/torch/utils/data/dataloader.py", line 385, in _next_data
    data = self._dataset_fetcher.fetch(index)  # may raise StopIteration
  File "/home/waq/anaconda3/envs/pytorch/lib/python3.6/site-packages/torch/utils/data/_utils/fetch.py", line 44, in fetch
    data = [self.dataset[idx] for idx in possibly_batched_index]
  File "/home/waq/anaconda3/envs/pytorch/lib/python3.6/site-packages/torch/utils/data/_utils/fetch.py", line 44, in <listcomp>
    data = [self.dataset[idx] for idx in possibly_batched_index]
  File "/root/slowfast/slowfast/datasets/ava_dataset.py", line 377, in __getitem__
    image_paths, backend=self.cfg.AVA.IMG_PROC_BACKEND
  File "/root/slowfast/slowfast/datasets/utils.py", line 36, in retry_load_images
    raise Exception("Failed to load images {}".format(image_paths))
Exception: Failed to load images ['/data/ava/frames/914yZXz-iRs/914yZXz-iRs_000029.jpg', '/data/ava/frames/914yZXz-iRs/914yZXz-iRs_000031.jpg', '/data/ava/frames/914yZXz-iRs/914yZXz-iRs_000033.jpg', '/data/ava/frames/914yZXz-iRs/914yZXz-iRs_000035.jpg', '/data/ava/frames/914yZXz-iRs/914yZXz-iRs_000037.jpg', '/data/ava/frames/914yZXz-iRs/914yZXz-iRs_000039.jpg', '/data/ava/frames/914yZXz-iRs/914yZXz-iRs_000041.jpg', ......

**Comment by lhyfst** [comment]
I encounter the same problem when I train the model on Charades.

**Comment by lhyfst** [comment]
I have solved this problem. Please check the paths in your csv file. They should be absolute paths.

You can use DATA.PATH_PREFIX to set the dataset path.

**Comment by wangaoqi-waq** [comment]
Thank you, I try。

**Comment by zhulishun** [comment]
@wangaoqi-waq @lhyfst @takatosp1 
 hi, when i Download videos AVA
DATA_DIR="../../data/ava/videos"

if [[ ! -d "${DATA_DIR}" ]]; then
  echo "${DATA_DIR} doesn't exist. Creating it.";
  mkdir -p ${DATA_DIR}
fi

wget https://s3.amazonaws.com/ava-dataset/annotations/ava_file_names_trainval_v2.1.txt

for line in $(cat ava_file_names_trainval_v2.1.txt)
do
  wget https://s3.amazonaws.com/ava-dataset/trainval/$line -P ${DATA_DIR}
done
 
BUT Connecting to s3.amazonaws.com (s3.amazonaws.com)|52.216.29.142|:443... failed: Connection timed out.
Retrying.

**Comment by poincarelee** [comment]
@wangaoqi-waq  have you solved the problem?
 I tried on HMDB51 dataset and met the same problem, then I changed paths in .csv files to absolute path, still the same error.
